import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Squad 02 - Um Sushi",
  description: "Generated by create next app (e Rian Bene)",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body>{children}</body>
    </html>
  );
}
